repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          "--remove-all-unused-imports",
          "--in-place",
        ]
        language_version: python3.11

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile=black"]
        language_version: python3.11

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        entry: pylint
        args: [
          "--max-args=6",
        ]
        language_version: python3.11
        additional_dependencies: [
          "docx2txt==0.8",
          "faiss-cpu==1.8.0",
          "langchain==0.1.13",
          "langchain-community==0.0.29",
          "langchain-openai==0.0.8",
          "openai==1.14.0",
          "pypdf==4.2.0",
          "pytest==8.1.1",
          "streamlit==1.33.0",
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        entry: mypy
        verbose: true
        language_version: python3.11
        additional_dependencies: []
